export const MAINTENANCE_STATUS = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
} as const;

export type MaintenanceStatus = (typeof MAINTENANCE_STATUS)[keyof typeof MAINTENANCE_STATUS];

export const MAINTENANCE_TYPE = {
  OIL_CHANGE: 'OIL_CHANGE',
  BRAKE_PADS: 'BRAKE_PADS',
  BRAKE_DISCS: 'BRAKE_DISCS',
  TIMING_BELT: 'TIMING_BELT',
  AIR_FILTER: 'AIR_FILTER',
  FUEL_FILTER: 'FUEL_FILTER',
  CABIN_FILTER: 'CABIN_FILTER',
  SPARK_PLUGS: 'SPARK_PLUGS',
  COOLANT: 'COOLANT',
  TRANSMISSION_OIL: 'TRANSMISSION_OIL',
  CUSTOM: 'CUSTOM',
} as const;

export type MaintenanceType = (typeof MAINTENANCE_TYPE)[keyof typeof MAINTENANCE_TYPE];

export const MAINTENANCE_URGENCY = {
  OVERDUE: 'OVERDUE',
  CRITICAL: 'CRITICAL',
  WARNING: 'WARNING',
  OK: 'OK',
  INACTIVE: 'INACTIVE',
} as const;

export type MaintenanceUrgency = (typeof MAINTENANCE_URGENCY)[keyof typeof MAINTENANCE_URGENCY];
