export const ERROR_CODES = {
  Auth: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',

    ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
    ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',

    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_REVOKED: 'SESSION_REVOKED',

    GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
    GOOGLE_EMAIL_MISSING: 'GOOGLE_EMAIL_MISSING',
  },

  Email: {
    ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
    CHANGE_PENDING: 'EMAIL_CHANGE_PENDING',
  },

  Token: {
    INVALID: 'TOKEN_INVALID',
    EXPIRED: 'TOKEN_EXPIRED',
    ALREADY_USED: 'TOKEN_ALREADY_USED',
    NOT_FOUND: 'TOKEN_NOT_FOUND',
  },

  User: {
    NOT_FOUND: 'USER_NOT_FOUND',
    PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
    PASSWORD_SAME: 'PASSWORD_SAME',
  },

  Workspace: {
    NOT_FOUND: 'WORKSPACE_NOT_FOUND',
    ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',
    INSUFFICIENT_ROLE: 'WORKSPACE_INSUFFICIENT_ROLE',
    OWNER_CANNOT_LEAVE: 'WORKSPACE_OWNER_CANNOT_LEAVE',
    ALREADY_MEMBER: 'WORKSPACE_ALREADY_MEMBER',

    INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
    INVITE_EXPIRED: 'INVITE_EXPIRED',
    INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
    INVITE_EMAIL_MISMATCH: 'INVITE_EMAIL_MISMATCH',
  },

  Vehicle: {
    NOT_FOUND: 'VEHICLE_NOT_FOUND',
    ACCESS_DENIED: 'VEHICLE_ACCESS_DENIED',
    INVALID_MILEAGE: 'VEHICLE_INVALID_MILEAGE',
  },

  Timeline: {
    EVENT_NOT_FOUND: 'TIMELINE_EVENT_NOT_FOUND',
    INVALID_MILEAGE: 'TIMELINE_INVALID_MILEAGE',
    INVALID_EVENT_TYPE: 'TIMELINE_INVALID_EVENT_TYPE',
    EVENT_ALREADY_EXISTS: 'TIMELINE_EVENT_ALREADY_EXISTS',
  },

  Reminder: {
    NOT_FOUND: 'REMINDER_NOT_FOUND',
    ALREADY_COMPLETED: 'REMINDER_ALREADY_COMPLETED',
    ALREADY_DISMISSED: 'REMINDER_ALREADY_DISMISSED',
  },

  Maintenance: {
    NOT_FOUND: 'MAINTENANCE_INTERVAL_NOT_FOUND',
    ALREADY_DISABLED: 'MAINTENANCE_INTERVAL_ALREADY_DISABLED',
  },

  Tire: {
    NOT_FOUND: 'TIRE_NOT_FOUND',
    ALREADY_MOUNTED: 'TIRE_ALREADY_MOUNTED',
    ALREADY_RETIRED: 'TIRE_ALREADY_RETIRED',
  },

  ServiceStation: {
    NOT_FOUND: 'SERVICE_STATION_NOT_FOUND',
    ACCESS_DENIED: 'SERVICE_STATION_ACCESS_DENIED',
  },

  Media: {
    NOT_FOUND: 'MEDIA_NOT_FOUND',
    UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
    INVALID_FILE_TYPE: 'MEDIA_INVALID_FILE_TYPE',
    FILE_TOO_LARGE: 'MEDIA_FILE_TOO_LARGE',
    ACCESS_DENIED: 'MEDIA_ACCESS_DENIED',
  },

  Ai: {
    CONVERSATION_NOT_FOUND: 'AI_CONVERSATION_NOT_FOUND',
    MESSAGE_FAILED: 'AI_MESSAGE_FAILED',
    SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  },

  General: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    NOT_FOUND: 'NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    CONFLICT: 'CONFLICT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  },
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES][keyof (typeof ERROR_CODES)[keyof typeof ERROR_CODES]];
