export const VALIDATION_CODES = {
  REQUIRED: 'REQUIRED',
  NOT_ALLOWED: 'NOT_ALLOWED',

  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_URL: 'INVALID_URL',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_ENUM: 'INVALID_ENUM',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_PLATE_NUMBER: 'INVALID_PLATE_NUMBER',
  INVALID_VIN: 'INVALID_VIN',
  INVALID_COLOR: 'INVALID_COLOR',

  TOO_SHORT: 'TOO_SHORT',
  TOO_LONG: 'TOO_LONG',

  TOO_SMALL: 'TOO_SMALL',
  TOO_LARGE: 'TOO_LARGE',
  MUST_BE_POSITIVE: 'MUST_BE_POSITIVE',
  MUST_BE_INTEGER: 'MUST_BE_INTEGER',

  ALREADY_EXISTS: 'ALREADY_EXISTS',
  MUST_MATCH: 'MUST_MATCH',
  MUST_BE_FUTURE: 'MUST_BE_FUTURE',
  MUST_BE_PAST: 'MUST_BE_PAST',
  MUST_BE_AFTER: 'MUST_BE_AFTER',
} as const;

export type ValidationCode = (typeof VALIDATION_CODES)[keyof typeof VALIDATION_CODES];
