export const TimelineConstraints = {
  // Shared
  TITLE_MIN: 1,
  TITLE_MAX: 100,
  DESCRIPTION_MAX: 1000,

  MILEAGE_MIN: 0,
  MILEAGE_MAX: 9_999_999,

  COST_MIN: 0,

  // Refuel
  LITERS_MIN: 0,
  LITERS_MAX: 999,

  PRICE_PER_LITER_MIN: 0,
  PRICE_PER_LITER_MAX: 100,

  // Charge
  KWH_MIN: 0,
  KWH_MAX: 500,

  PRICE_PER_KWH_MIN: 0,
  PRICE_PER_KWH_MAX: 100,

  BATTERY_PERCENT_MIN: 0,
  BATTERY_PERCENT_MAX: 100,

  CHARGER_NETWORK_MAX: 100,

  // Service
  WORKS_MAX_ITEMS: 50,
  PARTS_MAX_ITEMS: 50,

  WORK_NAME_MIN: 1,
  WORK_NAME_MAX: 100,
  WORK_DESCRIPTION_MAX: 500,

  PART_NAME_MIN: 1,
  PART_NAME_MAX: 100,
  PART_DESCRIPTION_MAX: 500,
  PART_QUANTITY_MIN: 1,
  PART_QUANTITY_MAX: 1000,

  // Document
  DOCUMENT_NUMBER_MAX: 100,
  ISSUED_BY_MAX: 100,

  // Trip
  DISTANCE_KM_MIN: 0,
  DISTANCE_KM_MAX: 99_999,

  START_LOCATION_MAX: 200,
  END_LOCATION_MAX: 200,

  // Purchase / Sale
  COUNTRY_MAX: 100,
} as const;
