import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  BadgePercent,
  Banknote,
  BarChart2,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  Bell,
  BellOff,
  BellRing,
  Bookmark,
  Bot,
  Boxes,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  CalendarX,
  Camera,
  Car,
  CarFront,
  CaseSensitive,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleDot,
  CircleQuestionMark,
  Clock,
  Cloud,
  Cog,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  DollarSign,
  DoorClosed,
  Dot,
  Download,
  Droplets,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FilePlus,
  FileText,
  FileX,
  Filter,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Fuel,
  Gauge,
  Gift,
  Globe,
  Grid2x2,
  Hammer,
  Hash,
  Heart,
  HeartOff,
  HelpCircle,
  Home,
  Image,
  Images,
  Inbox,
  Info,
  KeyRound,
  Laptop,
  Layers,
  LayoutGrid,
  Link,
  List,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailWarning,
  Map,
  MapPin,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Navigation,
  Navigation2,
  Package,
  Palette,
  PanelLeft,
  PanelRight,
  Paperclip,
  Phone,
  PiggyBank,
  Plus,
  Power,
  QrCode,
  Receipt,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  ScanLine,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  SlidersVertical,
  Smartphone,
  SortAsc,
  SortDesc,
  Sparkles,
  Star,
  StarOff,
  Sun,
  Tag,
  Tags,
  Thermometer,
  Timer,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  Video,
  Wallet,
  WifiOff,
  Wind,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

// ─── Icons Registry ───────────────────────────────────────────────────────────

export const Icons = {
  // Navigation
  home: Home,
  car: Car,
  mapPin: MapPin,
  bot: Bot,
  user: User,
  settings: Settings,
  menu: Menu,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  slidersVertical: SlidersVertical,

  // Actions
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash2,
  save: Save,
  copy: Copy,
  share: Share2,
  download: Download,
  upload: Upload,
  search: Search,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  refresh: RefreshCw,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  externalLink: ExternalLink,
  link: Link,

  // Status & Feedback
  check: Check,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  xCircle: XCircle,
  clock: Clock,
  loader: Loader2,
  circleAlert: CircleAlert,
  badgeCheck: BadgeCheck,
  mailWarning: MailWarning,
  circleQuestionMark: CircleQuestionMark,
  wifiOff: WifiOff,

  // Auth & User
  logIn: LogIn,
  logOut: LogOut,
  userPlus: UserPlus,
  userCheck: UserCheck,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  key: KeyRound,
  shield: Shield,

  // Vehicle
  fuel: Fuel,
  gauge: Gauge,
  wrench: Wrench,
  zap: Zap,
  thermometer: Thermometer,
  activity: Activity,
  barChart: BarChart2,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  carFront: CarFront,
  palette: Palette,
  doorClosed: DoorClosed,
  package: Package,
  cloud: Cloud,
  grid: Grid2x2,

  // Documents & Files
  fileText: FileText,
  file: File,
  filePlus: FilePlus,
  fileCheck: FileCheck,
  fileX: FileX,
  folder: Folder,
  folderOpen: FolderOpen,
  paperclip: Paperclip,
  receipt: Receipt,

  // Finance & Stats
  dollar: DollarSign,
  creditCard: CreditCard,
  wallet: Wallet,
  piggyBank: PiggyBank,
  percent: BadgePercent,
  banknote: Banknote,
  shoppingCart: ShoppingCart,

  // Time & Calendar
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  calendarPlus: CalendarPlus,
  calendarX: CalendarX,
  timer: Timer,
  bell: Bell,
  bellOff: BellOff,
  bellRing: BellRing,

  // Location & Map
  map: Map,
  navigation: Navigation,
  navigation2: Navigation2,
  crosshair: Crosshair,
  globe: Globe,
  phone: Phone,

  // Media
  image: Image,
  images: Images,
  camera: Camera,
  video: Video,
  mic: Mic,

  // UI & Layout
  layoutGrid: LayoutGrid,
  list: List,
  layers: Layers,
  tag: Tag,
  tags: Tags,
  star: Star,
  starOff: StarOff,
  heart: Heart,
  heartOff: HeartOff,
  bookmark: Bookmark,
  flag: Flag,
  circle: Circle,
  dot: Dot,
  hash: Hash,

  // Workspace & Team
  users: Users,
  userMinus: UserMinus,
  building: Building2,
  briefcase: Briefcase,
  crown: Crown,
  boxes: Boxes,

  // Tires & Service
  tireDot: CircleDot,
  hammer: Hammer,
  cog: Cog,
  cpu: Cpu,
  droplets: Droplets,
  wind: Wind,
  flame: Flame,
  batteryCharging: BatteryCharging,
  battery: Battery,
  batteryFull: BatteryFull,
  batteryLow: BatteryLow,

  // Misc
  qrCode: QrCode,
  scan: ScanLine,
  sparkles: Sparkles,
  trophy: Trophy,
  gift: Gift,
  helpCircle: HelpCircle,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  send: Send,
  inbox: Inbox,
  archive: Archive,
  trashAlt: Trash,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  maximize: Maximize2,
  minimize: Minimize2,
  panelLeft: PanelLeft,
  panelRight: PanelRight,
  sliders: SlidersHorizontal,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  power: Power,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
  smartphone: Smartphone,
  laptop: Laptop,
  caseSensitive: CaseSensitive,
} as const;

export type IconName = keyof typeof Icons;
