export const VEHICLE_BRANDS = [
  'Alfa Romeo',
  'Audi',
  'BMW',
  'Citroën',
  'Dacia',
  'Fiat',
  'Ford',
  'Honda',
  'Hyundai',
  'Jaguar',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Mazda',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Renault',
  'SEAT',
  'Škoda',
  'Smart',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Lancia',
  'Maserati',
  'Alfa Romeo',
  'DS',
  'Cupra',
  'Lada',
  'Trabant',
  'Genesis',
  'SsangYong',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Jeep',
  'Lincoln',
  'Daihatsu',
  'Isuzu',
  'Infiniti',
  'Acura',
  'BYD',
  'MG',
  'Xpeng',
  'Nio',
  'Lynk & Co',
  'Zeekr',
  'Omoda',
  'Jaecoo',
  'Chery',
  'Geely',
  'Great Wall',
  'Haval',
  'Dongfeng',
  'Citroën',
  'Fiat',
  'Ford',
  'Mercedes-Benz',
  'Peugeot',
  'Renault',
  'Volkswagen',
  'Opel',
  'Nissan',
  'Toyota',
] as const;

export const VEHICLE_MODELS: Record<string, string[]> = {
  'Alfa Romeo': [
    '145',
    '146',
    '147',
    '155',
    '156',
    '159',
    '164',
    '166',
    'Giulia',
    'Giulietta',
    'GT',
    'GTV',
    'MiTo',
    'Spider',
    'Stelvio',
    'Tonale',
    'Brera',
  ],
  Audi: [
    'A1',
    'A2',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q2',
    'Q3',
    'Q4 e-tron',
    'Q5',
    'Q7',
    'Q8',
    'TT',
    'TTS',
    'R8',
    'e-tron',
    'e-tron GT',
    'e-tron Sportback',
    '80',
    '90',
    '100',
    'Cabriolet',
    'RS3',
    'RS4',
    'RS5',
    'RS6',
    'RS7',
    'S3',
    'S4',
    'S5',
    'S6',
    'S8',
    'Allroad',
  ],
  BMW: [
    '1 Series',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'Z3',
    'Z4',
    'M2',
    'M3',
    'M4',
    'M5',
    'M6',
    'M8',
    'i3',
    'i4',
    'i5',
    'i7',
    'iX',
    'iX1',
    'iX3',
    'Gran Turismo',
    'Active Tourer',
    'Gran Coupe',
  ],
  Citroën: [
    'AX',
    'BX',
    'C1',
    'C2',
    'C3',
    'C3 Aircross',
    'C3 Picasso',
    'C4',
    'C4 Cactus',
    'C4 Picasso',
    'C5',
    'C5 Aircross',
    'C5 X',
    'C6',
    'C8',
    'DS3',
    'DS4',
    'DS5',
    'Berlingo',
    'Jumpy',
    'Spacetourer',
    'ë-C4',
    'ë-Berlingo',
    'ë-Spacetourer',
    'Saxo',
    'Xantia',
    'Xsara',
    'ZX',
  ],
  Cupra: ['Ateca', 'Born', 'Formentor', 'Leon', 'Tavascan', 'Terramar'],
  Dacia: [
    'Dokker',
    'Duster',
    'Jogger',
    'Lodgy',
    'Logan',
    'Logan MCV',
    'Sandero',
    'Sandero Stepway',
    'Spring',
  ],
  DS: ['DS 3', 'DS 3 Crossback', 'DS 4', 'DS 5', 'DS 7', 'DS 9'],
  Fiat: [
    '124 Spider',
    '127',
    '128',
    '500',
    '500C',
    '500L',
    '500X',
    '600',
    'Barchetta',
    'Bravo',
    'Croma',
    'Doblo',
    'Grande Punto',
    'Idea',
    'Linea',
    'Marea',
    'Multipla',
    'Palio',
    'Punto',
    'Qubo',
    'Scudo',
    'Sedici',
    'Stilo',
    'Tempra',
    'Tipo',
    'Ulysse',
    'Panda',
    'Seicento',
  ],
  Ford: [
    'B-Max',
    'C-Max',
    'EcoSport',
    'Edge',
    'Escape',
    'Explorer',
    'F-150',
    'Fiesta',
    'Focus',
    'Fusion',
    'Galaxy',
    'Grand C-Max',
    'Ka',
    'Ka+',
    'Kuga',
    'Mondeo',
    'Mustang',
    'Mustang Mach-E',
    'Puma',
    'Ranger',
    'S-Max',
    'Tourneo Connect',
    'Tourneo Custom',
    'Transit',
    'Transit Connect',
    'Transit Custom',
    'Probe',
    'Cougar',
    'Maverick',
  ],
  Genesis: ['G70', 'G80', 'G90', 'GV70', 'GV80', 'GV60'],
  Honda: [
    'Accord',
    'City',
    'Civic',
    'Concerto',
    'CR-V',
    'CR-X',
    'e',
    'e:Ny1',
    'FR-V',
    'HR-V',
    'Insight',
    'Jazz',
    'Legend',
    'Logo',
    'NSX',
    'Prelude',
    'Stream',
    'ZR-V',
  ],
  Hyundai: [
    'Accent',
    'Atos',
    'Coupe',
    'Elantra',
    'Getz',
    'Grand Santa Fe',
    'i10',
    'i20',
    'i30',
    'i40',
    'IONIQ',
    'IONIQ 5',
    'IONIQ 6',
    'ix20',
    'ix35',
    'ix55',
    'Kona',
    'Nexo',
    'Santa Fe',
    'Sonata',
    'Terracan',
    'Trajet',
    'Tucson',
    'Veloster',
  ],
  Jaguar: ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'S-Type', 'X-Type', 'XE', 'XF', 'XJ'],
  Jeep: [
    'Avenger',
    'Cherokee',
    'Commander',
    'Compass',
    'Grand Cherokee',
    'Patriot',
    'Renegade',
    'Wrangler',
  ],
  Kia: [
    'Carens',
    'Carnival',
    'Ceed',
    'EV6',
    'EV9',
    'Niro',
    'Picanto',
    'ProCeed',
    'Rio',
    'Sorento',
    'Soul',
    'Sportage',
    'Stinger',
    'Stonic',
    'Venga',
    'XCeed',
  ],
  Lada: [
    '2101',
    '2104',
    '2105',
    '2106',
    '2107',
    '2108',
    '2109',
    '2110',
    'Granta',
    'Kalina',
    'Largus',
    'Niva',
    'Priora',
    'Vesta',
    'XRAY',
  ],
  'Land Rover': [
    'Defender',
    'Discovery',
    'Discovery Sport',
    'Freelander',
    'Range Rover',
    'Range Rover Evoque',
    'Range Rover Sport',
    'Range Rover Velar',
  ],
  Lexus: ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX', 'RZ'],
  'Lynk & Co': ['01', '02', '03'],
  Mazda: [
    '2',
    '3',
    '5',
    '6',
    '121',
    '323',
    '626',
    'CX-3',
    'CX-30',
    'CX-5',
    'CX-60',
    'CX-80',
    'CX-90',
    'MX-5',
    'MX-30',
    'RX-7',
    'RX-8',
    'Premacy',
    'Tribute',
  ],
  'Mercedes-Benz': [
    'A-Class',
    'B-Class',
    'C-Class',
    'CLA',
    'CLS',
    'E-Class',
    'EQA',
    'EQB',
    'EQC',
    'EQE',
    'EQS',
    'G-Class',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'S-Class',
    'SL',
    'SLK',
    'SLS AMG',
    'V-Class',
    'Vito',
    'Sprinter',
    'ML-Class',
    'GL-Class',
    'CLK',
    'AMG GT',
  ],
  MG: ['3', '4', '5', 'EHS', 'Marvel R', 'MG ZS', 'One', 'ZS EV'],
  Mini: [
    'Cabrio',
    'Clubman',
    'Convertible',
    'Countryman',
    'Coupe',
    'Hatch',
    'One',
    'Paceman',
    'Cooper',
    'Cooper S',
    'John Cooper Works',
    'Electric',
    'Countryman Electric',
  ],
  Mitsubishi: [
    'ASX',
    'Carisma',
    'Colt',
    'Eclipse Cross',
    'Galant',
    'Grandis',
    'L200',
    'Lancer',
    'Outlander',
    'Pajero',
    'Pajero Sport',
    'Space Star',
    'Eclipse',
  ],
  Nissan: [
    '350Z',
    '370Z',
    'Almera',
    'Ariya',
    'Juke',
    'Leaf',
    'Micra',
    'Murano',
    'Navara',
    'Note',
    'Pathfinder',
    'Patrol',
    'Pixo',
    'Primera',
    'Pulsar',
    'Qashqai',
    'Sunny',
    'Terrano',
    'Tiida',
    'X-Trail',
    'NV200',
  ],
  Omoda: ['5', '7', 'E5'],
  Opel: [
    'Adam',
    'Agila',
    'Astra',
    'Calibra',
    'Cascada',
    'Combo',
    'Corsa',
    'Crossland',
    'Frontera',
    'Grandland',
    'Insignia',
    'Meriva',
    'Mokka',
    'Omega',
    'Signum',
    'Sintra',
    'Tigra',
    'Vectra',
    'Vivaro',
    'Zafira',
    'Ampera',
    'Mokka-e',
    'Corsa-e',
  ],
  Peugeot: [
    '106',
    '107',
    '108',
    '205',
    '206',
    '207',
    '208',
    '301',
    '306',
    '307',
    '308',
    '405',
    '406',
    '407',
    '408',
    '5008',
    '508',
    '605',
    '607',
    '2008',
    '3008',
    '4007',
    '4008',
    'Bipper',
    'Partner',
    'Rifter',
    'Traveller',
    'e-208',
    'e-2008',
  ],
  Porsche: ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  Renault: [
    'Arkana',
    'Austral',
    'Captur',
    'Clio',
    'Espace',
    'Express',
    'Fluence',
    'Grand Scenic',
    'Kadjar',
    'Kangoo',
    'Koleos',
    'Laguna',
    'Latitude',
    'Master',
    'Megane',
    'Modus',
    'Rafale',
    'Safrane',
    'Scenic',
    'Symbol',
    'Thalia',
    'Trafic',
    'Twingo',
    'Vel Satis',
    'Zoe',
    'Megane E-Tech',
    'Scenic E-Tech',
    'R5',
    '19',
    '21',
    '25',
  ],
  SEAT: [
    'Alhambra',
    'Altea',
    'Arona',
    'Ateca',
    'Cordoba',
    'Exeo',
    'Ibiza',
    'Leon',
    'Mii',
    'Tarraco',
    'Toledo',
  ],
  Škoda: [
    'Citigo',
    'Enyaq',
    'Fabia',
    'Felicia',
    'Kamiq',
    'Karoq',
    'Kodiaq',
    'Kodiaq RS',
    'Octavia',
    'Octavia RS',
    'Rapid',
    'Roomster',
    'Scala',
    'Superb',
    'Yeti',
    'Enyaq Coupe',
  ],
  Smart: ['Forfour', 'Fortwo', '#1', '#3'],
  SsangYong: ['Actyon', 'Korando', 'Musso', 'Rexton', 'Rodius', 'Tivoli', 'XLV'],
  Subaru: [
    'BRZ',
    'Forester',
    'Impreza',
    'Justy',
    'Legacy',
    'Levorg',
    'Outback',
    'Solterra',
    'Tribeca',
    'WRX',
    'XV',
  ],
  Suzuki: [
    'Alto',
    'Baleno',
    'Celerio',
    'Grand Vitara',
    'Ignis',
    'Jimny',
    'Kizashi',
    'Liana',
    'S-Cross',
    'Splash',
    'Swift',
    'SX4',
    'Vitara',
    'Wagon R+',
  ],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],
  Toyota: [
    'Auris',
    'Avensis',
    'Aygo',
    'bZ4X',
    'C-HR',
    'Camry',
    'Carina',
    'Celica',
    'Corolla',
    'Crown',
    'GR Yaris',
    'GT86',
    'Hilux',
    'Land Cruiser',
    'MR2',
    'Paseo',
    'Previa',
    'Prius',
    'Prius+',
    'ProAce',
    'RAV4',
    'Sequoia',
    'Starlet',
    'Supra',
    'Urban Cruiser',
    'Verso',
    'Yaris',
    'Yaris Cross',
    'GR86',
    'Highlander',
  ],
  Volkswagen: [
    'Amarok',
    'Arteon',
    'Beetle',
    'Bora',
    'Caddy',
    'California',
    'Caravelle',
    'CC',
    'Crafter',
    'Eos',
    'Fox',
    'Golf',
    'Golf Sportsvan',
    'ID.3',
    'ID.4',
    'ID.5',
    'ID.6',
    'ID.7',
    'Jetta',
    'Lupo',
    'Multivan',
    'Passat',
    'Phaeton',
    'Polo',
    'Scirocco',
    'Sharan',
    'T-Cross',
    'T-Roc',
    'Tiguan',
    'Tiguan Allspace',
    'Touareg',
    'Touran',
    'Transporter',
    'Up',
    'Vento',
  ],
  Volvo: [
    'C30',
    'C40',
    'C70',
    'EX30',
    'EX40',
    'EX90',
    'S40',
    'S60',
    'S70',
    'S80',
    'S90',
    'V40',
    'V50',
    'V60',
    'V70',
    'V90',
    'XC40',
    'XC60',
    'XC70',
    'XC90',
  ],
  BYD: ['Atto 3', 'Han', 'Seal', 'Tang', 'Song Plus', 'Dolphin', 'Seagull', 'Shark'],
  Xpeng: ['G3', 'G6', 'G9', 'P5', 'P7', 'X9'],
  Nio: ['ES6', 'ES7', 'ES8', 'ET5', 'ET7', 'EL6', 'EC6'],
  Zeekr: ['001', '007', '009', 'X'],
  Jaecoo: ['J7', 'J8'],
  Chery: ['Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Omoda 5'],
  Geely: ['Emgrand', 'Atlas', 'Coolray', 'Tugella'],
  'Great Wall': ['Hover H5', 'Hover H6', 'Wingle'],
  Haval: ['F7', 'H6', 'Jolion', 'H9'],
  Dongfeng: ['AX7', 'S30', 'A30'],
  Cadillac: ['ATS', 'CT4', 'CT5', 'CT6', 'Escalade', 'SRX', 'XT4', 'XT5', 'XT6', 'XTS'],
  Chevrolet: [
    'Aveo',
    'Camaro',
    'Captiva',
    'Corvette',
    'Cruze',
    'Epica',
    'Equinox',
    'Lacetti',
    'Malibu',
    'Niva',
    'Orlando',
    'Spark',
    'Tahoe',
    'Trailblazer',
    'Trax',
  ],
  Chrysler: ['300', '300C', 'Grand Voyager', 'Neon', 'PT Cruiser', 'Sebring', 'Stratus', 'Voyager'],
  Dodge: ['Avenger', 'Caliber', 'Challenger', 'Charger', 'Durango', 'Journey', 'Nitro', 'Ram'],
  Lincoln: ['Aviator', 'Continental', 'Corsair', 'MKC', 'MKX', 'MKZ', 'Nautilus', 'Navigator'],
  Daihatsu: ['Charade', 'Cuore', 'Materia', 'Move', 'Rocky', 'Sirion', 'Terios', 'YRV'],
  Infiniti: ['EX', 'FX', 'G', 'M', 'Q30', 'Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX60', 'QX70'],
  Lancia: ['Delta', 'Kappa', 'Lybra', 'Musa', 'Phedra', 'Thesis', 'Ypsilon', 'Zeta'],
  Maserati: ['Ghibli', 'GranCabrio', 'GranTurismo', 'Grecale', 'Levante', 'Quattroporte'],
  Trabant: ['601', '1.1'],
  Acura: ['ILX', 'MDX', 'RDX', 'RLX', 'TL', 'TLX', 'TSX'],
  Isuzu: ['D-Max', 'Mu-X', 'Trooper'],
};

export const VEHICLE_POPULAR_BRANDS = [
  'Volkswagen',
  'Toyota',
  'Škoda',
  'Ford',
  'Opel',
  'BMW',
  'Audi',
  'Mercedes-Benz',
  'Peugeot',
  'Kia',
] as const;

export type VehicleBrand = keyof typeof VEHICLE_MODELS;
